### PR TITLE
New Auth Flow changes

### PR DESCRIPTION
**Pull request by sachin-maheshwari**

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
@sachin-maheshwari can you please check why the build fails https://app.circleci.com/pipelines/github/topcoder-platform/topcoder-payment-tool/26/workflows/5f1179e4-6e2b-4ff8-be23-a93bd15ddb10/jobs/88 ?

**Comment by sachin-maheshwari** [comment]
@ThomasKranitsas sure, I'll check today.

**Comment by sachin-maheshwari** [comment]
@ThomasKranitsas that is unit testing issue due to new babel version, please fix accordingly.

**Comment by ThomasKranitsas** [comment]
@sachin-maheshwari Are you sure? Because tests and build pass and works fine on my local if I use the correct node version. Maybe it's the node version that's making it fail?

**Comment by sachin-maheshwari** [comment]
@ThomasKranitsas I am sure, as same is working fine at my local env too. But issue reproduce locally if you delete package-lock.json and after deleting node_modules folder, do "npm install" again, its fail on "npm test".

**Comment by ThomasKranitsas** [comment]
@sachin-maheshwari why are we deleting the lock file though?

**Comment by sachin-maheshwari** [comment]
@ThomasKranitsas if we ignore that, build will success but app will not work. so I think, need to fix the npm dependencies. 
- https://github.com/topcoder-platform/topcoder-payment-tool/commit/41dd20826a7580e2e39506d523fd337dae32cef3 
Screenshot 2021-01-15 at 6 57 42 PM

**Comment by sachin-maheshwari** [comment]
@ThomasKranitsas i have fixed the build issues, please feel free to modify in your way. 
https://app.circleci.com/pipelines/github/topcoder-platform/topcoder-payment-tool/30/workflows/76dc739d-e89f-442c-b170-56f2326560f9/jobs/92

**Comment by ThomasKranitsas** [comment]
Thanks @sachin-maheshwari !

**Pull request merged**
